version: '3.3'

services:
  app:
    image: 'user-service:latest'
    build:
      context: .
    container_name: user-service
    depends_on:
      - user_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user_db:5432/user_db?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8
    ports:
      - 8080:8080
  user_db:
    image: 'postgres:latest'
    container_name: user_db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"