spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user_db?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8}
    username: user
    password: 123
  flyway:
    enabled: true
    validate-on-migrate: true
  data:
    web:
      pageable:
        default-page-size: 50
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
logging:
  level:
    root: INFO
    web: ERROR
    sql: ERROR
  file:
    name: ./logs/user-service.log
